// =============================================================
//  選手別動画テーブル (window.PLAYER_VIDEOS)
//  - 試合中(game.js)と、選手カードの「動画」ボタン(card_view.js)の両方で使う共有データ。
//    カード追加画面(import.html)は game.js を読み込まないため、ここに切り出している。
//  - 動画ファイルは MLB/douga/ に {接頭辞}_{カテゴリ}.mp4 / {接頭辞}_{カテゴリ}1.mp4 … の名前で置く。
//  - 「動画変換リスト」更新時に編集するのはこのファイル (game.js 側は参照するだけ)。
// =============================================================
(function(){
'use strict';

// 選手別動画: 打者カードの fullNameTop (例 "Aaジャッジ") → 動画ファイル接頭辞。
//   対応が無い選手/カテゴリは従来通り defobat_ 系にフォールバックする。格納先は同じ MLB/douga/。
const PLAYER_VIDEO_PREFIX = {
  'Aaジャッジ': 'judge',
  'Jaチゾム': 'chisholm',
  'Trグリシャム': 'grisham',
  'Coベリンジャー': 'bellinger',
  'Anボルピー': 'volpe',
  'DJラメイヒュー': 'lemahieu',
  'Giスタントン': 'stanton',
  'Frコルデロ': 'fr_cordero',
  'Pゴールドシュミット': 'goldschmidt',
  'Osペラザ': 'peraza',
  'Paレイエス': 'pa_Reyes',
  'Joバーティー': 'berti',
  'Osカブレラ': 'os_Cabrera',
  'Alブレグマン': 'bregman',
  'Trストーリー': 'story',
  'Jaデュラン': 'ja_Duran',
  'Roレフスナイダー': 'refsnyder',
  'Abトロ': 'toro',
  '吉田正尚': 'yoshida',
  'Reマグワイヤー': 'mcGuire',
  'Trカサス': 'casas',
  'Brラウ': 'b_Lowe',
  'Yaディアス': 'y_Diaz',
  'Daジャンセン': 'd_Jansen',
  'Tyウォールズ': 'walls',
  'Chモレル': 'morel',
  'キム・ハソン': 'ha_Kim',
  'Geスプリンガー': 'springer',
  'VlゲレーロJr': 'guerrero',
  'Boビシェット': 'bichette',
  'Alカーク': 'kirk',
  'Myストロー': 'straw',
  'Daバーショ': 'varsho',
  'Anヒメネス': 'gimenez',
  'Anサンタンダー': 'santander',
  'Gaヘンダーソン': 'gu_Henderson',
  'Raローレアーノ': 'laureano',
  'Ryオーハン': 'o_Hearn',
  'Adラッチマン': 'rutschman',
  'Raウリアス': 'r_Urias',
  'Geサンチェス': 'g_sanchez',
  'Ceマリンズ': 'mullins',
  'Joマテオ': 'j_Mateo',
  'Rマウントキャッスル': 'mountcastle',
  'Dyカールソン': 'Carlson',
  'Haベイダー': 'bader',
  'Byバクストン': 'buxton',
  'Wiカストロ': 'w_Castro',
  'Ryジェファーズ': 'jeffers',
  'Caコレア': 'correa',
  'Tyフランス': 'france',
  'Chバスケス': 'c_vazquez',
  'Joラミレス': 'j_Ramirez',
  'Caサンタナ': 'c_Santana',
  'Laトーマス': 'l_Thomas',
  'Auヘッジス': 'hedges',
  'LuロバートJr': 'l_Robert',
  'Anベニンテンディ': 'benintendi',
  'MAテイラー': 'ma_Taylor',
  'Joロハス': 'j_Rojas',
  'Auスレイター': 'slater',
  'Baルース': 'ruth',
  'Miマントル': 'm_Mantle',
  'Wiメイズ': 'w_Mays',
  'Roクレメンテ': 'r_Clemente',
  'Joベンチ': 'j_Bench',
  'Daパーカー': 'd_parker',
  'Ozスミス': 'o_Smith',
  'KeグリフィーJr': 'griffey',
  'Deジーター': 'jeter',
  'Baボンズ': 'Bonds',
  'イチロー': 'ichiro',
  'Buポージー': 'posey',
  'Yaモリーナ': 'y_Molina',
  'チェ・ジマン': 'j_Choi',
  '筒香嘉智': 'tsutsugo',
  'Saペレス': 's_Perez',
  'Joインディア': 'india',
  'Kyイズベル': 'isbel',
  'Caビジオ': 'biggio',
  'Huレンフロー': 'renfroe',
  'Maカナ': 'canha',
  'Glトーレス': 'torres',
  'Jaバエズ': 'j_Baez',
  'Anイバニェス': 'ibanez',
  'Jaロジャース': 'j_Rogers',
  'Toニード': 'nido',
  'Jaマイヤーズ': 'j_Meyers',
  'Joアルトゥーベ': 'altuve',
  'Chウォーカー': 'c_Walker',
  'Yoアルバレス': 'alvarez',
  'Zaショート': 'short',
  'Viカラティーニ': 'caratini',
  'Brロジャース': 'b_Rodgers',
  'Chマコーミック': 'mcCormick',
  'Miトラウト': 'trout',
  'Taウォード': 'ward',
  'Yoモンカダ': 'moncada',
  'Luレンフィーフォ': 'rengifo',
  'Trダーノウ': 'd_Arnaud',
  'Joソレーア': 'soler',
  'Chテイラー': 'c_Taylor',
  'Keニューマン': 'newman',
  'Tiアンダーソン': 't_Anderson',
  'Luウリアス': 'l_Urias',
  'Auウィンズ': 'wynns',
  'Giアーシェラ': 'urshela23',
  'Seブラウン': 's_Brown',
  'JPクロフォード': 'jp_Crawford',
  'Caローリー': 'raleigh',
  'Joポランコ': 'j_Polanco',
  'Raアロザレーナ': 'arozarena',
  'Dyムーア': 'd_Moore',
  'Miガーバー': 'garver',
  'Viロブレス': 'v_Robles',
  'Doソラーノ': 'solano',
  'Luレイリー': 'l_Raley',
  'Coシーガー': 'c_Seager',
  'Maシミエン': 'semien',
  'Kyヒガシオカ': 'higashioka',
  'Adガルシア': 'ad_Garcia',
  'Tuバーンハート': 'barnhart',
  'Joハイム': 'heim',
  'Joピーダーソン': 'pederson',
  'Keピラー': 'pillar',
  'Roグロスマン': 'grossman',
  'Maオルソン': 'olson',
  'RoアクーニャJr': 'acuna',
  'Seマーフィー': 's_Murphy',
  'Auライリー': 'riley',
  'Ozオルビース': 'albies',
  'Juプロファー': 'profar',
  'Maオズーナ': 'ozuna',
  'Alバデューゴ': 'verdugo',
  'Brデラクルーズ': 'de_La_Cruz',
  'Daフレッチャー': 'fletcher',
  'Jaケルニック': 'kelenic',
  'Jeサンチェス': 'j_Sanchez',
  'Frリンドーア': 'lindor',
  'Juソト': 'soto',
  'Brニモ': 'nimmo',
  'Peアロンゾ': 'alonso',
  'Jeマクニール': 'mcNeil',
  'Luトーレンス': 'torrens',
  'Tyテイラー': 'ty_Taylor',
  'Stマルテ': 's_Marte',
  'Joシリ': 'siri',
  'Jeウィンカー': 'winker',
  'Trターナー': 't_Turner',
  'Kyシュワーバー': 'schwarber',
  'Brハーパー': 'harper',
  'Edソーサ': 'e_Sosa',
  'Maケプラー': 'kepler',
  'Brマーシュ': 'marsh',
  'Alボーム': 'bohm',
  'Niカステヤノス': 'castellanos',
  'JTリアルミュート': 'realmuto',
  'Brストット': 'stott',
  'Daダール': 'dahl',
  'Gaスタッブス': 'stubbs',
  'Joベル': 'bell',
  'Amロサリオ': 'a_Rosario',
  'CJエイブラムス': 'abrams',
  'Paデヨング': 'deJong',
  'Naロウ': 'n_lowe',
  'Keルイーズ': 'k_Ruiz',
  'Kyタッカー': 'tucker',
  'Iaハップ': 'i_Happ',
  'Caケリー': 'c_Kelly',
  'Daスワンソン': 'swanson',
  'Niホーナー': 'hoerner',
  'Juターナー': 'j_Turner',
  'Reマグワイア': 'mcGuire',
  'Tスティーブンソン': 'stephenson',
  'Auヘイズ': 'a_Hays',
  'Gaラックス': 'lux',
  'Jeキャンデラリオ': 'candelario',
  'Saエスピナル': 'espinal',
  'Joトレビーニョ': 'j_Trevino',
  'Coジョー': 'c_Joe',
  'Jaフレイリー': 'fraley',
  'Chイエリッチ': 'yelich',
  'Rhホスキンス': 'hoskins',
  'Waコントレラス': 'w_Contreras',
  'Anボーン': 'vaughn',
  'Jaバウアーズ': 'j_Bauers',
  'Erハース': 'haase',
  'Toファム': 'pham',
  'Onクルーズ': 'o_Cruz',
  'Brレイノルズ': 'reynolds',
  'カイナーファレファ': 'k_Falefa',
  'KeBヘイズ': 'k_Hayes',
  'Adフレイジャー': 'a_Frazier',
  'Anマカッチェン': 'mcCutchen',
  'Jaスウィンスキー': 'suwinski',
  'Wsコントレラス': 'contreras',
  'Brドノバン': 'donovan',
  'Laヌートバー': 'nootbaar',
  'Noアレナド': 'arenado',
  'Geペルドモ': 'g_Perdomo',
  'Keマーテイ': 'k_Marte',
  'Euスアレス': 'e_Suarez',
  'LoグリエルJr': 'l_Gurriel',
  'Paスミス': 'pa_Smith',
  'Joネイラー': 'j_Naylor',
  'Jaマッキャン': 'j_McCann',
  'Alトーマス': 'a_Thomas',
  'Raグリチック': 'grichuk',
  'Saヒリアード': 'hilliard',
  'Ryマクマーン': 'mcMahon',
  'Kyファーマー': 'farmer',
  'Jaスターリングス': 'stallings',
  'Thエストラーダ': 't_Estrada',
  'Wiスミス': 'w_Smith',
  '大谷翔平': 'ohtani',
  'Frフリーマン': 'freeman',
  'Maマンシー': 'muncy',
  'Moベッツ': 'betts',
  'Teヘルナンデス': 't_Hernandez',
  'Toエドマン': 'edman',
  'Miロハス': 'm_Rojas',
  'Enヘルナンデス': 'e_hernandez',
  'Auバーンズ': 'a_Barnes',
  'Miコンフォルト': 'conforto',
  'Jクローネンワース': 'cronenworth',
  'FeタティースJr': 'tatis',
  'Gaシーツ': 'sheets',
  'Maマチャード': 'machado',
  'Daペラルタ': 'd_Peralta',
  'Elディアズ': 'el_Diaz',
  'Luアラエズ': 'arraez',
  'Xaボガーツ': 'bogaerts',
  'Jaヘイワード': 'heyward',
  'Maマルドナード': 'maldonado',
  'Joイグレシアス': 'j_iglesias',   // 動画ファイルは box のみ大文字(j_Iglesias_box)だが Windows は大小同一視で再生可
  'Yuグリエル': 'y_Gurriel',
  'Mヤストレムスキー': 'yastrzemski',
  'Raデバース': 'devers',
  'Maチャップマン': 'm_Chapman',
  'Wiアダーメス': 'w_Adames',
  'Wiフローレス': 'w_Flores',
  'Doスミス': 'do_Smith',
  'Anキズナー': 'knizner',
  'LaウェイドJr': 'wade',
  'Joモーガン': 'j_Morgan',
  'Alロドリゲス': 'a_Rod',
  'Peローズ': 'p_Rose',
  'Miシュミット': 'm_Schmidt',
  'Jaロビンソン': 'j_Robinson',
  'Hoワグナー': 'h_Wagner',
  'Teウィリアムズ': 'te_Williams',
  'Riヘンダーソン': 'r_Henderson',
  'Yoベラ': 'y_Berra',
  'Frロビンソン': 'f_Robinson',
  'Roホーンスビー': 'hornsby',
  'Tyカッブ': 't_Cobb',
  'Joディマジオ': 'diMaggio',
  'Stミュージアル': 'musial',
  'Loゲーリッグ': 'l_Gehrig',
  'Haアーロン': 'h_Aaron',
};
// 選手別動画のカテゴリ毎バリエーション数 (1=固定で毎回同じ、2以上=ランダム choice)。
//   box=打者登場 / hr,2b,if1b,rbi,1b,fb,miss=打席結果 /
//   ste=盗塁成功(走者本人) / throw=盗塁阻止(捕手が走者を刺す映像) /
//   fp=守備でファインプレーした際の本人映像 (無い選手は投手の nice 動画にフォールバック)。
//   カテゴリが無い(0扱い)場合は defobat_ にフォールバックする。
const PLAYER_VIDEO_VARIANTS = {
  judge:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 2, fp: 1 },
  chisholm:  { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  grisham:   { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  bellinger: { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  volpe:     { box: 2, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1, fp: 1 },
  lemahieu:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  stanton:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  fr_cordero:  { box: 1 },
  goldschmidt: { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  peraza:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  pa_Reyes:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1, fp: 1 },
  berti:       { box: 1 },
  os_Cabrera:  { box: 2, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1, fp: 2 },
  bregman:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  story:       { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  ja_Duran:    { box: 2, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1, fp: 1 },
  refsnyder:   { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  toro:        { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  yoshida:     { box: 2, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  mcGuire:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, throw: 1 },
  casas:       { box: 2, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  b_Lowe:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1, fp: 1 },
  y_Diaz:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  d_Jansen:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, throw: 1 },
  walls:       { box: 2, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1, fp: 2 },
  morel:       { box: 1 },
  ha_Kim:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  springer:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  guerrero:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 2 },
  bichette:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1, fp: 1 },
  kirk:        { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, throw: 1 },
  straw:       { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1, fp: 1 },
  varsho:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  gimenez:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1 },
  santander:   { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  gu_Henderson: { box: 3, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1, fp: 2 },
  laureano:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  o_Hearn:     { box: 1, rbi: 1 },
  rutschman:   { box: 2, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 2, throw: 1, fp: 1 },
  r_Urias:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  g_sanchez:   { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, throw: 1 },
  mullins:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1, fp: 1 },
  j_Mateo:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1, fp: 1 },
  mountcastle: { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  Carlson:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  bader:       { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  buxton:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, ste: 1 },
  w_Castro:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  jeffers:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, throw: 1 },
  correa:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  france:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  c_vazquez:   { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, throw: 1 },
  j_Ramirez:   { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, ste: 1 },
  c_Santana:   { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  l_Thomas:    { box: 1 },
  hedges:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, throw: 1 },
  l_Robert:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  benintendi:  { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  ma_Taylor:   { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  j_Rojas:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  slater:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  ruth:        { box: 1, hr: 2 },
  m_Mantle:    { box: 1, hr: 2 },
  w_Mays:      { box: 2, hr: 2, '2b': 1, rbi: 1, '1b': 1, fp: 1 },
  r_Clemente:  { box: 1, hr: 2, '2b': 1, rbi: 1, '1b': 1, fp: 1 },
  j_Bench:     { box: 2, hr: 2, '2b': 1, throw: 1, fp: 1 },
  d_parker:    { box: 2, hr: 2, '2b': 1, rbi: 1, fb: 1, fp: 1 },
  o_Smith:     { box: 2, hr: 1, '2b': 1, rbi: 1, fp: 3 },
  griffey:     { box: 1, hr: 2, '2b': 1, rbi: 1, '1b': 2, fp: 1 },
  jeter:       { box: 2, hr: 2, '2b': 1, rbi: 2, '1b': 2, fp: 1 },
  Bonds:       { box: 2, hr: 2, '2b': 1, rbi: 1, '1b': 1 },
  ichiro:      { box: 3, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 2 },
  posey:       { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  y_Molina:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  j_Choi:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  tsutsugo:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  s_Perez:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  india:       { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  isbel:       { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  biggio:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 2, ste: 1, fp: 1 },
  renfroe:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  canha:       { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  torres:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1 },
  j_Baez:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  ibanez:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  j_Rogers:    { box: 1, rbi: 1 },
  nido:        { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  j_Meyers:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  altuve:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  c_Walker:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  alvarez:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  short:       { box: 1 },
  caratini:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  b_Rodgers:   { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  mcCormick:   { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  trout:       { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 2, ste: 1, fp: 1 },
  ward:        { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  moncada:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  rengifo:     { box: 2, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1, fp: 1 },
  d_Arnaud:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, throw: 1 },
  soler:       { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  c_Taylor:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1 },
  newman:      { box: 1 },
  t_Anderson:  { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1 },
  l_Urias:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  wynns:       { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, throw: 1 },
  urshela23:   { box: 2, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  s_Brown:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  jp_Crawford: { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  raleigh:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  j_Polanco:   { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1 },
  arozarena:   { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, ste: 1 },
  d_Moore:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  garver:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, throw: 1 },
  v_Robles:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  solano:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  l_Raley:     { box: 2, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, ste: 1 },
  c_Seager:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  semien:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  higashioka:  { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, throw: 1 },
  ad_Garcia:   { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1 },
  barnhart:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  heim:        { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  pederson:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  pillar:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  grossman:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  olson:       { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  acuna:       { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 2, fp: 1, ste: 1 },
  s_Murphy:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, throw: 1 },
  riley:       { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  albies:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, ste: 1 },
  profar:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  ozuna:       { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  verdugo:     { box: 1, hr: 1, '2b': 2, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, ste: 1 },
  de_La_Cruz:  { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  fletcher:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, ste: 1 },
  kelenic:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  j_Sanchez: { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  lindor:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  soto:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 2 },
  nimmo:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  alonso:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  mcNeil:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  torrens:   { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  ty_Taylor: { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  s_Marte:   { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  siri:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  winker:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  t_Turner:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  schwarber:   { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  harper:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  e_Sosa:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  kepler:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, ste: 1 },
  marsh:       { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, ste: 1 },
  bohm:        { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  castellanos: { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  realmuto:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  stott:       { box: 1 },
  dahl:        { box: 1 },
  stubbs:      { box: 1 },
  bell:        { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  a_Rosario:   { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1 },
  abrams:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  deJong:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  n_lowe:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  k_Ruiz:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  tucker:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, ste: 1 },
  i_Happ:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  c_Kelly:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  swanson:     { box: 2, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, ste: 1 },
  hoerner:     { box: 1, hr: 1 },
  j_Turner:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  stephenson:  { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  a_Hays:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  lux:         { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  candelario:  { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  espinal:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, ste: 1 },
  j_Trevino:   { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  c_Joe:       { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  fraley:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  yelich:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  hoskins:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  w_Contreras: { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, throw: 1 },
  vaughn:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  j_Bauers:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  haase:       { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  pham:        { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  o_Cruz:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  reynolds:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  k_Falefa:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  k_Hayes:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  a_Frazier:   { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  mcCutchen:   { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  suwinski:    { box: 1 },
  contreras:   { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  donovan:     { box: 1 },
  nootbaar:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  arenado:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  g_Perdomo:   { box: 1 },
  k_Marte:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  e_Suarez:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  l_Gurriel:   { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  pa_Smith:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  j_Naylor:    { box: 1, hr: 1, '2b': 1, if1b: 1, '1b': 2 },   // rbi/fb動画は無し
  j_McCann:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  a_Thomas:    { box: 1 },
  grichuk:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, ste: 1 },
  hilliard:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  mcMahon:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  farmer:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  stallings:   { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  t_Estrada:   { box: 1 },
  w_Smith:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, throw: 1 },
  ohtani:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1 },   // 二刀流: 投手側は PITCHER_VIDEO_VARIANTS に別途登録
  freeman:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 2 },
  muncy:       { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 2 },
  betts:       { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 2, fp: 1, ste: 1 },
  t_Hernandez: { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  edman:       { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  m_Rojas:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  e_hernandez: { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  a_Barnes:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, throw: 1 },
  conforto:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  cronenworth: { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  tatis:       { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  sheets:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  machado:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  d_Peralta:   { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  el_Diaz:     { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  arraez:      { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  bogaerts:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, ste: 1 },
  heyward:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  maldonado:   { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1, throw: 1 },
  j_iglesias:  { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  y_Gurriel:   { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  yastrzemski: { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  devers:      { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  m_Chapman:   { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  w_Adames:    { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1, fp: 1 },
  w_Flores:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  do_Smith:    { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  knizner:     { box: 1, hr: 1, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  wade:        { box: 1, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fb: 1 },
  j_Morgan:    { box: 2, hr: 2, '2b': 1, rbi: 1, '1b': 1, ste: 1 },
  a_Rod:       { box: 2, hr: 2, '2b': 1, if1b: 1, rbi: 1, '1b': 2, fp: 1 },
  p_Rose:      { box: 2, hr: 1, '2b': 2, rbi: 1, '1b': 1 },
  m_Schmidt:   { box: 1, hr: 2, rbi: 1, fp: 1 },
  j_Robinson:  { box: 1, hr: 1, '2b': 1, ste: 1 },
  h_Wagner:    { box: 2 },
  te_Williams: { box: 2, hr: 2, '2b': 1, rbi: 2, '1b': 2 },
  r_Henderson: { box: 1, hr: 1, ste: 2, fp: 1 },
  y_Berra:     { box: 1, hr: 1 },
  f_Robinson:  { box: 2, hr: 2 },
  hornsby:     { box: 1 },
  t_Cobb:      { box: 2, hr: 1 },
  diMaggio:    { box: 1, hr: 2, '2b': 1 },
  musial:      { box: 2, hr: 2, '2b': 1 },
  l_Gehrig:    { box: 1, hr: 2 },
  h_Aaron:     { box: 1, hr: 2 },
};
// 投手別動画: 投手カードの fullNameTop (例 "Maフリード") → 動画ファイル接頭辞。
//   対応が無い投手は従来通り defopit_ 系にフォールバックする。格納先は同じ MLB/douga/。
const PITCHER_VIDEO_PREFIX = {
  'Maフリード': 'fried',
  'Caロドン': 'rodon',
  'Luウィーバー': 'l_Weaver',
  'Caカラスコ': 'c_Carrasco',
  'Maストローマン': 'stroman',
  'Tiヒル': 't_Hill',
  'JTブルベイカー': 'brubaker',
  'Deウィリアムズ': 'd_Williams',
  'Ryヤーブロー': 'yarbrough',
  'Jaロアイシガ': 'loaisiga',
  'Gaクロシェ': 'crochet',
  'Luジオリト': 'giolito',
  'Waビューラー': 'buehler',
  'Juウィルソン': 'j_Wilson',
  'Gaウィットロック': 'whitlock',
  'Arチャップマン': 'chapman',
  'Taハウク': 'houck',
  'Drラスムセン': 'rasmussen',
  'Zaリッテル': 'littell',
  'Shバズ': 'baz',
  'Coサルサー': 'sulser',
  'Peフェアバンクス': 'fairbanks',
  'Tyアレクサンダー': 'alexander',
  'Aaシバーレ': 'civale',
  'Keゴーズマン': 'gausman',
  'Chバシット': 'bassitt',
  'Joべリオス': 'berrios',
  'Erラウアー': 'lauer',
  'Maシャーザー': 'scherzer',
  'Niサンドリン': 'sandlin',
  'Jeホフマン': 'j_Hoffman',
  'Shビーバー': 'bieber',
  'Joウレーニャ': 'urena',
  'Chグリーン': 'c_green',
  'Trロジャース': 'tr_Rogers',
  'Deクレマー': 'kremer',
  'Chモートン': 'morton',
  'Grソト': 'g_Soto',
  'Keエイキン': 'akin',
  'Anキトリッジ': 'kittredge',
  'Zaエフリン': 'eflin',
  'Tyウェルズ': 't_Wells',
  'Chパダック': 'paddack',
  'Baオーバー': 'ober',
  'Paロペス': 'p_Lopez',
  'Daクーロム': 'coulombe',
  'Grジャックス': 'jax',
  'Joアルカラ': 'alcala',
  'Geカブレラ': 'ge_Cabrera',
  'Jaジュニス': 'junis',
  'Koアラード': 'allard',
  'Emクラッセ': 'clase',
  'Paシーウォルド': 'sewald',
  'Adハウザー': 'houser',
  'Aaシバーリ': 'civale',
  'Tyギルバート': 't_Gilbert',
  'Maペレス': 'm_perez',
  'Roクレメンス': 'clemens',
  'Raジョンソン': 'r_Johnson',
  'Scシールズ': 's_Shields',
  'Tiリンスカム': 'lincecum',
  'RAディッキー': 'ra_Dickey',
  'ダルビッシュ有': 'darvish',
  'Clカーショー': 'kershaw',
  'Brボックスバーガー': 'boxberger',
  'Geコール': 'cole',
  'Krブービッチ': 'bubic',
  'Seルーゴ': 'lugo',
  'Miロレンゼン': 'lorenzen',
  'Caエステベス': 'c_Estevez',
  'Daリンチ': 'lynch',
  'Chストラットン': 'stratton',
  'Taスクーバル': 'skubal',
  'Jaフラハティ': 'flaherty',
  'Caマイズ': 'mize',
  'Frバルデス': 'f_Valdez',
  'Stオカート': 'okert',
  'Joヘイダー': 'hader',
  'Crハビア': 'javier',
  'LaマカラーズJr': 'mcCullers',
  '菊池雄星': 'kikuchi',
  'Tyアンダーソン': 't_Anderson23',
  'Coブログドン': 'brogdon',
  'Reデトマーズ': 'detmers',
  'Keジャンセン': 'jansen',
  'Heネリス': 'neris',
  'Jeスプリングス': 'springs',
  'TJマクファーランド': 'mcFarland',
  'Luカスティーヨ': 'l_Castillo',
  'Loギルバート': 'gilbert',
  'Trソーントン': 't_Thornton',
  'Jaデグローム': 'deGrom',
  'Naイオバルディ': 'eovaldi',
  'Paコービン': 'corbin',
  'Tyマーリー': 'mahle',
  'Chマーティン': 'c_Martin',
  'Jaウェブ': 'j_Webb',
  'Luジャクソン': 'l_Jackson',
  'Joグレイ': 'jon_Gray',
  'Daダニング': 'dunning',
  'Chセール': 'sale',
  'Aaバマー': 'bummer',
  'Piジョンソン': 'p_Johnson',
  'Raイグレシアス': 'iglesias',
  'Joスアレス': 'j_suarez',
  'Edカブレラ': 'ed_Cabrera',
  'Saアルカンタラ': 'alcantara',
  'Caクワントリル': 'quantrill',
  'Anベンダー': 'bender',
  'Ryウェザーズ': 'weathers',
  'Daピーターソン': 'd_Peterson',
  'Clホームズ': 'holmes',
  'Grキャニング': 'canning',
  'Ryスタネック': 'stanek',
  'Brレイリー': 'raley',
  'Edディアズ': 'e_Diaz',
  'Seマナエア': 'manaea',
  'Tyメギル': 'megill',
  'Frモンタス': 'montas',
  'Paブラックバーン': 'blackburn',
  'Jeルザード': 'luzardo',
  'Zaウィーラー': 'z_Wheeler',
  'Raスアレス': 'r_Suarez',
  'Taウォーカー': 't_Walker',
  'Joアルバラード': 'alvarado',
  'Caヘルナンデス': 'ca_Hernandez',
  'Joロマーノ': 'romano',
  'Aaノラ': 'a_Nola',
  'Joロス': 'j_Ross',
  'Joルイーズ': 'j_Ruiz',
  'Jaアービン': 'irvin',
  'Trウィリアムズ': 't_Williams',
  'Anチェイフィン': 'chafin',
  'Kyフィネガン': 'finnegan',
  'Joロペス': 'j_Lopez',
  'Maボイド': 'boyd',
  'Jaタイオン': 'taillon',
  'Caシールバー': 'thielbar',
  'Chフレクセン': 'flexen',
  'Ryプレスリー': 'pressly',
  'Brケラー': 'b_Keller',
  'Drポメランツ': 'pomeranz',
  'Juスティール': 'steele',
  'Brシンガー': 'singer',
  'Scバーロウ': 'barlow',
  'Taロジャース': 'rogers',
  'Brスーター': 'suter',
  'Toサンティラン': 'santillan',
  'Emパガーン': 'pagan',
  'Waマイリー': 'miley',
  'Frペラルタ': 'f_Peralta',
  'Brウッドラフ': 'woodruff',
  'Niミアーズ': 'mears',
  'Aaアシュビー': 'ashby',
  'Trメギル': 'megill',
  'Miケラー': 'mi_Keller',
  'Baファルター': 'falter',
  'Anヒーニー': 'heaney',
  'Deサンタナ': 'de_Santana',
  'Daべドナー': 'bednar',
  'Yoラミレス': 'y_Ramirez',
  'Soグレイ': 's_Gray',
  'Miマイコラス': 'mikolas',
  'Erフェッディ': 'fedde',
  'Stマッツ': 'matz',
  'Phメイトン': 'maton',
  'Ryヘルズリー': 'helsley',
  'Joキング': 'j_King',
  'Meケリー': 'me_Kelly',
  'Zaギャレン': 'z_Gallen',
  'Edロドリゲス': 'e_rodriguez',
  'Ryトンプソン': 'thompson',
  'Joカーティス': 'curtiss',
  'Naクリスマット': 'crismatt',
  'Coバーンズ': 'c_Burnes',
  'Jaウッドフォード': 'woodford',
  'Aディスクラファニ': 'deSclafani',
  'Joマンティプライ': 'mantiply',
  'Kyフリーランド': 'freeland',
  'Anセンザテラ': 'senzatela',
  'Geマルケス': 'marquez',
  'Tyキンリー': 'kinley',
  'Jiハーゲット': 'herget',
  'Auゴンバー': 'gomber',
  '大谷翔平': 'ohtani',
  'Tyグラスノー': 'glasnow',
  'Anバンダ': 'banda',
  'Loトリビーノ': 'trivino',
  'Alベシア': 'vesia',
  'Taスコット': 't_Scott',
  'Blスネル': 'b_Snell',
  'Toゴンソリン': 'gonsolin',
  'Niピベッタ': 'pivetta',
  'Dyシース': 'cease',
  'Waペラルタ': 'w_Peralta',
  'Neコルテス': 'cortes',
  'Miキング': 'king',
  'Loウェブ': 'l_Webb',
  'Roレイ': 'r_Ray',
  'Juバーランダー': 'j_Verlander',
  'Tyロジャース': 't_Rogers',
  'Joヒックス': 'j_Hicks',
  // ===== 過去の名投手 (レジェンド) =====
  'Cyヤング': 'cy_Young',
  'Toシーバー': 't_Seaver',
  'Noライアン': 'n_Ryan',
  'Sコーファックス': 'koufax',
  'Roフィンガーズ': 'r_Fingers',
  'Boギブソン': 'b_Gibson',
  'Toゴードン': 'to_Gordon',
  'Luアヤラ': 'l_Ayala',
  'Arローズ': 'a_Rhodes',
  'Alライター': 'a_Leiter',
  'Baジト': 'zito',
  'Grマダックス': 'maddux',
  'Peマルティネス': 'p_Martinez',
  'Waジョンソン': 'w_Johnson',
  '野茂英雄': 'nomo',
  'Maリベラ': 'm_Rivera',
};
// 投手別動画のカテゴリ毎バリエーション数 (1=固定で毎回同じ、2以上=ランダム choice)。
//   sta=登板(マウンドへ) / tou=投球イントロ / str=三振 / nice=ファインプレー /
//   miss=エラー(該当野手動画が無いため投手ががっかりする動画で代用)。
const PITCHER_VIDEO_VARIANTS = {
  fried: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  rodon: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  l_Weaver:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  c_Carrasco: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  stroman:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  t_Hill:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  brubaker:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  d_Williams: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  yarbrough:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  loaisiga:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  crochet:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  giolito:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  buehler:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  j_Wilson: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  whitlock: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  chapman:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  houck:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  rasmussen: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  littell:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  baz:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  sulser:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  fairbanks: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  alexander: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  civale:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  gausman:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  bassitt:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  berrios:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  lauer:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  scherzer:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  sandlin:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  j_Hoffman: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  bieber:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  urena:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  c_green:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  tr_Rogers: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  kremer:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  morton:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  g_Soto:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  akin:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  kittredge: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  eflin:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  t_Wells:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  paddack:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  ober:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  p_Lopez:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  coulombe:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  jax:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  alcala:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  ge_Cabrera: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  junis:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  allard:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  clase:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  sewald:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  houser:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  t_Gilbert: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  m_perez:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  clemens:   { sta: 1, tou: 3, str: 6, nice: 1, miss: 1 },
  r_Johnson: { sta: 1, tou: 3, str: 6, nice: 1, miss: 1 },
  s_Shields: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  lincecum:  { sta: 1, tou: 3, str: 5, nice: 1, miss: 1 },
  ra_Dickey: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  darvish:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  kershaw:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  boxberger: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  cole:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  bubic:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  lugo:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  lorenzen:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  c_Estevez: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  lynch:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  stratton:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  skubal:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  flaherty:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  mize:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  f_Valdez:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  okert:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  hader:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  javier:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  mcCullers: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  kikuchi:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  t_Anderson23: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  brogdon:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  detmers:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  jansen:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  neris:        { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  springs:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  mcFarland:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  l_Castillo:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  gilbert:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  t_Thornton:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  deGrom:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  eovaldi:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  corbin:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  mahle:        { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  c_Martin:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  j_Webb:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  l_Jackson:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  jon_Gray:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  dunning:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  sale:         { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  bummer:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  p_Johnson:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  iglesias:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  j_suarez:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  ed_Cabrera: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  alcantara:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  quantrill:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  bender:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  weathers:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  d_Peterson: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  holmes:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  canning:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  stanek:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  raley:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  e_Diaz:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  manaea:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  megill:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  montas:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  blackburn:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  luzardo:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  z_Wheeler:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  r_Suarez:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  t_Walker:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  alvarado:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  ca_Hernandez: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  romano:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  a_Nola:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  j_Ross:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  j_Ruiz:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  irvin:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  t_Williams: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  chafin:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  finnegan:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  j_Lopez:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  boyd:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  taillon:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  thielbar:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  flexen:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  pressly:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  b_Keller:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  pomeranz:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  steele:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  singer:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  barlow:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  rogers:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  suter:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  santillan:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  pagan:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  miley:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  f_Peralta:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  woodruff:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  mears:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  ashby:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  mi_Keller:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  falter:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  heaney:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  de_Santana: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  bednar:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  y_Ramirez:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  s_Gray:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  mikolas:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  fedde:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  matz:        { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  maton:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  helsley:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  j_King:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  me_Kelly:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  z_Gallen:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  e_rodriguez: { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  thompson:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  curtiss:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  crismatt:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  c_Burnes:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  woodford:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  deSclafani:  { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  mantiply:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  freeland:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  senzatela:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  marquez:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  kinley:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  herget:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  gomber:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  ohtani:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },   // 二刀流: 打者側は PLAYER_VIDEO_VARIANTS に別途登録
  glasnow:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  banda:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  trivino:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  vesia:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  t_Scott:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  b_Snell:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  gonsolin:    { sta: 1, tou: 3, str: 3, miss: 1 },   // nice動画は無し (投手のniceにフォールバック)
  pivetta:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  cease:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  w_Peralta:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  cortes:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  king:        { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  l_Webb:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  r_Ray:       { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  j_Verlander: { nice: 1 },   // ファインプレー動画のみ (他カテゴリは defopit_ にフォールバック)
  t_Rogers:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  j_Hicks:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  // ===== 過去の名投手 (レジェンド) =====
  cy_Young:    { sta: 1 },   // 登板動画のみ (他カテゴリは defopit_ にフォールバック)
  t_Seaver:    { sta: 1, tou: 3, str: 5, nice: 1, miss: 1 },
  n_Ryan:      { sta: 2, tou: 3, str: 6, nice: 1, miss: 1 },
  koufax:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  r_Fingers:   { sta: 1, tou: 3, str: 6, nice: 1, miss: 1 },
  b_Gibson:    { sta: 1, tou: 3, str: 5, nice: 1, miss: 1 },
  to_Gordon:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  l_Ayala:     { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  a_Rhodes:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  a_Leiter:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  zito:        { sta: 1, tou: 3, str: 5, nice: 1, miss: 1 },
  maddux:      { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  p_Martinez:  { sta: 1, tou: 3, str: 5, nice: 1, miss: 1 },
  w_Johnson:   { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  nomo:        { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
  m_Rivera:    { sta: 1, tou: 3, str: 3, nice: 1, miss: 1 },
};

// ---- 選手カードの「動画」ボタン用: カテゴリの日本語名 (表示順) ----
const BATTER_CATEGORIES = [
  ['box',   'バッターボックス'],
  ['1b',    'ヒット'],
  ['2b',    '長打 (2・3塁打)'],
  ['if1b',  '内野安打'],
  ['rbi',   'タイムリーヒット'],
  ['hr',    'ホームラン'],
  ['fb',    '四球'],
  ['ste',   '盗塁成功'],
  ['throw', '盗塁阻止'],
  ['fp',    'ファインプレー (守備)'],
];
const PITCHER_CATEGORIES = [
  ['sta',  '選手交代 (登板)'],
  ['tou',  '投球時'],
  ['str',  '奪三振'],
  ['nice', 'ファインプレー'],
  ['miss', 'エラー (がっかり)'],
];
// 動画ファイル名 → 再生URL (card_game/ からの相対パス。game.js の videoSrc と同じ置き場)
function fileUrl(file) { return '../douga/' + file + '.mp4'; }
// 接頭辞とカテゴリから、登録本数ぶんのファイル名リストを返す (0本なら空配列)
function filesOf(prefix, variants, cat) {
  const n = (prefix && variants[prefix] && variants[prefix][cat]) || 0;
  const list = [];
  for (let i = 0; i < n; i++) list.push(prefix + '_' + cat + (i === 0 ? '' : i));
  return list;
}
// 選手カードに登録されている専用動画の一覧を返す。
//   返り値: [{ kind:'batter'|'pitcher', cat, label, files:[ファイル名…] }, …] (登録が1本も無ければ空配列)
//   打者/投手の両方に登録がある選手(二刀流)は両方を返す。
function listFor(player) {
  const name = player && player.fullNameTop;
  const out = [];
  if (!name) return out;
  const bp = PLAYER_VIDEO_PREFIX[name];
  if (bp) for (const [cat, label] of BATTER_CATEGORIES) {
    const files = filesOf(bp, PLAYER_VIDEO_VARIANTS, cat);
    if (files.length) out.push({ kind: 'batter', cat, label, files });
  }
  const pp = PITCHER_VIDEO_PREFIX[name];
  if (pp) for (const [cat, label] of PITCHER_CATEGORIES) {
    const files = filesOf(pp, PITCHER_VIDEO_VARIANTS, cat);
    if (files.length) out.push({ kind: 'pitcher', cat, label, files });
  }
  return out;
}

window.PLAYER_VIDEOS = {
  batterPrefix: PLAYER_VIDEO_PREFIX,
  batterVariants: PLAYER_VIDEO_VARIANTS,
  pitcherPrefix: PITCHER_VIDEO_PREFIX,
  pitcherVariants: PITCHER_VIDEO_VARIANTS,
  BATTER_CATEGORIES, PITCHER_CATEGORIES,
  fileUrl, listFor,
};
})();
